# Changes here will be overwritten by Copier
_commit: v0.4.2
_src_path: gl:openscm/copier-basic-python-repository
email: hoegner@iiasa.ac.at
name: Annika Högner
notebooks: true
package_manager: uv
project_description_short: prototype for the causal variability module in SCALES
project_url: https://github.com/eahoegner/scales_causal
